export const ROUTE_HOME = '/'
export const ROUTE_LOGIN = '/login'
export const ROUTE_REGISTER = '/register'
export const ROUTE_SETTINGS = '/settings'
export const ROUTE_PROFILE = '/profile'
export const ROUTE_CREATE_ARTICLES = '/editor'
export const ROUTE_ARTICLE = '/article/:idArticle'
